/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Universidad.Vistas;

import Universidad.AccesoaDatos.AlumnoData;
import static Universidad.AccesoaDatos.AlumnoData.mostrarMensaje;
import Universidad.AccesoaDatos.Conectar;
import Universidad.Entidades.Alumno;
import java.sql.*;
import java.time.LocalDate;
import java.time.ZoneId;
        
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;



public class GestionAlumnos extends javax.swing.JFrame {

    public int auxId;
    
    public GestionAlumnos() {
        super("Alumnos");
        initComponents();
         setIconImage(new ImageIcon(getClass().getResource("/contenido/icon.png")).getImage());
        this.setLocationRelativeTo(null);
          
    }

    public void limpiar(){
            jtDoc.setText("");
            jtApellido.setText("");
            jtNombre.setText("");
            jdFechaNac.setDate(null);
            jrbEstado.setSelected(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPgestion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtDoc = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jdFechaNac = new com.toedter.calendar.JDateChooser();
        jrbEstado = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        jPgestion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contenido/alum.png"))); // NOI18N
        jLabel1.setText("ALUMNO");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPgestion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 24, 199, 53));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setText("Documento");
        jPgestion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 111, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setText("Apellido");
        jPgestion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 166, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setText("Nombre");
        jPgestion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 217, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setText("Estado");
        jPgestion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 263, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setText("Fecha de Nacimiento");
        jPgestion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jtDoc.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtDoc.setToolTipText("");
        jtDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDocActionPerformed(evt);
            }
        });
        jtDoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtDocKeyTyped(evt);
            }
        });
        jPgestion.add(jtDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 107, 189, -1));

        jtApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtApellidoKeyTyped(evt);
            }
        });
        jPgestion.add(jtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 162, 189, -1));

        jtNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNombreKeyTyped(evt);
            }
        });
        jPgestion.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 213, 189, 24));

        jbBuscar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jPgestion.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 103, -1, -1));

        jbNuevo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jPgestion.add(jbNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 377, -1, -1));

        jbEliminar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.setEnabled(false);
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jPgestion.add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 377, -1, -1));

        jbGuardar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jPgestion.add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 377, -1, -1));

        jbSalir.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPgestion.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 377, 64, -1));
        jPgestion.add(jdFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 306, 151, -1));

        jrbEstado.setBorder(null);
        jPgestion.add(jrbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 258, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contenido/fondoventana.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPgestion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 510, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPgestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPgestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDocActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        Alumno al = new Alumno();
       
        if (jtDoc.getText().isEmpty()) {
            mostrarMensaje("Ingrese un dni para buscar el Alumno.", "Error al buscar", "error");
        } else {
            
            boolean aux;
            if(AlumnoData.buscarAlumnoPorDni(Integer.parseInt(jtDoc.getText()),0)!=null){
                al=AlumnoData.buscarAlumnoPorDni(Integer.parseInt(jtDoc.getText()),0);
                if (al.getActivo() == 1 ) {
                aux = true;
            } else{
                aux = false;
            }
            jtDoc.setText(al.getDni() + "");
            jtApellido.setText(al.getApellido());
            jtNombre.setText(al.getNombre());
            jdFechaNac.setDate(java.sql.Date.valueOf(al.getFechaNacimiento()));
            jrbEstado.setSelected(aux);
            if(!al.getApellido().isEmpty()){
                jbEliminar.setEnabled(true);
                jbGuardar.setEnabled(true);
                this.auxId=al.getIdAlumno();
            }
            }
            
            
        }

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        
        int aux;

        if (jtDoc.getText().isEmpty() || jtApellido.getText().isEmpty() || jtNombre.getText().isEmpty() || jdFechaNac.getDate() == null) {
            mostrarMensaje("Todos o alguno de los campos se encuentran vacios, por favor rellene todos.", "Error al crear Alumno", "error");
        } else {
            if(AlumnoData.buscarAlumnoPorDni(Integer.parseInt(jtDoc.getText()),1)!=null){
                mostrarMensaje("El Alumno que desea agregar ya existe.", "Error al crear Alumno", "error");
            }else{
            
            if (jrbEstado.isSelected()) {
                aux = 1;
            } else {
                aux = 0;
            }
            LocalDate fecha = jdFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            java.sql.Date jdate = java.sql.Date.valueOf(fecha);
            Alumno alumno = new Alumno(jtNombre.getText(), jtApellido.getText(), Integer.parseInt(jtDoc.getText()), fecha, aux);
            AlumnoData.guardarAlumno(alumno);
            limpiar();
            jbEliminar.setEnabled(false);
            jbGuardar.setEnabled(false);
        }   }
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        MenuPrincipal menu=new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jtDocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDocKeyReleased
        
    }//GEN-LAST:event_jtDocKeyReleased

    private void jtDocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDocKeyTyped
        int key=evt.getKeyChar();
        boolean num= key>=48 && key<=57;
        if(!num){
            evt.consume();
        }
        
        if(jtDoc.getText().length()>=8){
           evt.consume();
       }
    }//GEN-LAST:event_jtDocKeyTyped

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        AlumnoData.eliminarAlumno(auxId);
        jbGuardar.setEnabled(false);
        jbEliminar.setEnabled(false);
        limpiar();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        int aux;
        
        if (jtDoc.getText().isEmpty() || jtApellido.getText().isEmpty() || jtNombre.getText().isEmpty() || jdFechaNac.getDate() == null) {
            mostrarMensaje("Todos o alguno de los campos se encuentran vacios, por favor rellene todos.", "Error al crear Alumno", "error");
        }else{
            if (jrbEstado.isSelected()) {
                aux = 1;
            } else {
                aux = 0;
            }

            Alumno alumno=new Alumno(auxId,jtNombre.getText(), jtApellido.getText(), Integer.parseInt(jtDoc.getText()), jdFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),aux);
            AlumnoData.modificarAlumno(alumno);
            jbGuardar.setEnabled(false);
            jbEliminar.setEnabled(false);
            limpiar();
        }     
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApellidoKeyTyped
        char key = evt.getKeyChar();
        boolean letra = Character.isLetter(key)|| Character.isWhitespace(key);
        if (!letra) {
            evt.consume();
        }
    }//GEN-LAST:event_jtApellidoKeyTyped

    private void jtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNombreKeyTyped
        char key = evt.getKeyChar();
        boolean letra = Character.isLetter(key)|| Character.isWhitespace(key);
        if (!letra) {
            evt.consume();
        }
    }//GEN-LAST:event_jtNombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPgestion;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private com.toedter.calendar.JDateChooser jdFechaNac;
    private javax.swing.JCheckBox jrbEstado;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtDoc;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
