
package Universidad.Vistas;


import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



public class MenuPrincipal extends javax.swing.JFrame {

    
    public MenuPrincipal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/contenido/icon.png")).getImage());
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Root = new javax.swing.JPanel();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemFormAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemGestionMaterias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemManejoInscripciones = new javax.swing.JMenuItem();
        itemManipulacionNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemConsultaAlumnoPorMateria = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RootLayout = new javax.swing.GroupLayout(Root);
        Root.setLayout(RootLayout);
        RootLayout.setHorizontalGroup(
            RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        RootLayout.setVerticalGroup(
            RootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        jMenu1.setText("Alumno");

        itemFormAlumno.setText("Formulario de Alumno");
        itemFormAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFormAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(itemFormAlumno);

        jMenuBar.add(jMenu1);

        jMenu2.setText("Materia");

        itemGestionMaterias.setText("Formulario de Materia");
        itemGestionMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(itemGestionMaterias);

        jMenuBar.add(jMenu2);

        jMenu3.setText("Administracion");

        itemManejoInscripciones.setText("Manejo de Inscripciones");
        itemManejoInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManejoInscripcionesActionPerformed(evt);
            }
        });
        jMenu3.add(itemManejoInscripciones);

        itemManipulacionNotas.setText("Manipulacion de Notas");
        itemManipulacionNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManipulacionNotasActionPerformed(evt);
            }
        });
        jMenu3.add(itemManipulacionNotas);

        jMenuBar.add(jMenu3);

        jMenu4.setText("Consultas");

        itemConsultaAlumnoPorMateria.setText("Alumnos por Materia");
        itemConsultaAlumnoPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultaAlumnoPorMateriaActionPerformed(evt);
            }
        });
        jMenu4.add(itemConsultaAlumnoPorMateria);

        jMenuBar.add(jMenu4);

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmSalir.add(jMenuItem1);

        jMenuBar.add(jmSalir);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Root, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemManejoInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManejoInscripcionesActionPerformed
       Desktop.removeAll();
       Desktop.repaint();
       FormulariodeInscripciones fi = new FormulariodeInscripciones();
       fi.setVisible(true);
       Desktop.add(fi);
       Desktop.moveToFront(fi);
    }//GEN-LAST:event_itemManejoInscripcionesActionPerformed

    private void itemFormAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFormAlumnoActionPerformed
       Desktop.removeAll();
       Desktop.repaint();
       GestionAlumnos ga = new GestionAlumnos();
       ga.setVisible(true);
       Desktop.add(ga);
       Desktop.moveToFront(ga);
    }//GEN-LAST:event_itemFormAlumnoActionPerformed

    private void itemGestionMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionMateriasActionPerformed
       Desktop.removeAll();
       Desktop.repaint();
       GestionMaterias gm = new GestionMaterias();
       gm.setVisible(true);
       Desktop.add(gm);
       Desktop.moveToFront(gm);
    }//GEN-LAST:event_itemGestionMateriasActionPerformed

    private void itemManipulacionNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManipulacionNotasActionPerformed
       Desktop.removeAll();
       Desktop.repaint();
       gestionNotas gn = new gestionNotas();
       gn.setVisible(true);
       Desktop.add(gn);
       Desktop.moveToFront(gn);
    }//GEN-LAST:event_itemManipulacionNotasActionPerformed

    private void itemConsultaAlumnoPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaAlumnoPorMateriaActionPerformed
       Desktop.removeAll();
       Desktop.repaint();
       ConsultaAlumnoPorMateria cam = new ConsultaAlumnoPorMateria();
       cam.setVisible(true);
       Desktop.add(cam);
       Desktop.moveToFront(cam);
    }//GEN-LAST:event_itemConsultaAlumnoPorMateriaActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int opcion=JOptionPane.showConfirmDialog(null, "Esta seguro que desea salir?", "", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            // El usuario seleccionó "Sí", realiza la acción correspondiente
            System.exit(0);
        }   
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JPanel Root;
    private javax.swing.JMenuItem itemConsultaAlumnoPorMateria;
    private javax.swing.JMenuItem itemFormAlumno;
    private javax.swing.JMenuItem itemGestionMaterias;
    private javax.swing.JMenuItem itemManejoInscripciones;
    private javax.swing.JMenuItem itemManipulacionNotas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmSalir;
    // End of variables declaration//GEN-END:variables
}
